#!/bin/bash

echo "🔑 Cloudflare API Token Setup Guide"
echo "===================================="
echo ""
echo "1. Open: https://dash.cloudflare.com/profile/api-tokens"
echo "2. Click 'Create Token'"
echo "3. Use template 'Edit zone DNS'"
echo "4. Select zone: morloksmaze.com"
echo "5. Click 'Continue to summary'"
echo "6. Click 'Create Token'"
echo "7. Copy the token (starts with something like: 1234abcd...)"
echo ""
echo "Once you have the token, run:"
echo "export CF_TOKEN='your-token-here'"
echo "./setup-letsencrypt-cloudflare-auto.sh"
echo ""
echo "Or if you prefer, I can set up the direct method instead:"
echo "./setup-letsencrypt-direct.sh"