name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  frontend-build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./src/frontend
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: './src/frontend/package-lock.json'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build frontend
      run: npm run build
      
  backend-build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./src/backend
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: './src/backend/package-lock.json'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build backend
      run: npm run build

  docker-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build frontend Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./src/frontend
        push: false
        load: true
        tags: psscript-frontend:latest
        
    - name: Test frontend Docker image
      run: |
        docker image inspect psscript-frontend:latest