name: Docker Build and Test

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker images
      run: |
        docker-compose -f docker-compose.prod.yml build
    
    - name: Run tests
      run: |
        docker-compose -f docker-compose.prod.yml up -d
        # Wait for services to start
        sleep 20
        # Run backend tests
        docker-compose -f docker-compose.prod.yml exec -T backend npm test || true
        # Shutdown services
        docker-compose -f docker-compose.prod.yml down
    
    - name: Check Docker images
      run: docker images
